apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-flask-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-flask
  template:
    metadata:
      labels:
        app: todo-flask
    spec:
      containers:
        - name: todo-flask
          image: kuxha/todo-k8s-demo:v1
          imagePullPolicy: Always
          env:
            - name: MONGO_HOST
              value: "mongo-service"
            - name: MONGO_PORT
              value: "27017"
            - name: FLASK_ENV
              value: "production"
            - name: PORT
              value: "5000"
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: todo-flask-service
spec:
  selector:
    app: todo-flask
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 30080
  type: NodePort
